
#pragma once

#include <stdexcept>

namespace cppli {
    class cli_error;

    class error : public std::runtime_error {
    private:
        int error_code_;

        friend class cli_error;

        /// constructor for accessing negative errors codes. Accessed by cppli::cli_error (which is a friend)
        inline error(const std::string& what, int error_code) : std::runtime_error(what), error_code_(error_code) {}

    public:
        inline int error_code() const {
            return error_code_;
        }

        /// error code is unsigned because negative values are reserved for errors generated by cppli
        inline error(const std::string& what, uint16_t error_code) : std::runtime_error(what), error_code_(error_code) {}
        inline error(const char*        what, uint16_t error_code) : std::runtime_error(what), error_code_(error_code) {}

    };
}